"use strict";
// Bundles src/ (plain CommonJS, zero dependencies) into a single browser file
// exposing window.FoundryTranspile, and embeds a curated set of examples as
// window.FoundryExamples. No bundler dependency — a ~40-line require shim is
// all the transpiler needs.  Run: node playground/build.js
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");

function collect(dir, out) {
  for (const f of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, f.name);
    if (f.isDirectory()) collect(p, out);
    else if (f.name.endsWith(".js")) out.push(p);
  }
  return out;
}

// ---- module bundle -----------------------------------------------------------
const files = collect(path.join(ROOT, "src"), []);
let out = "// generated by playground/build.js — do not edit\n(function () {\nconst __mods = {};\nconst __cache = {};\n";
for (const f of files) {
  const key = path.relative(ROOT, f).replace(/\\/g, "/");
  out += `__mods[${JSON.stringify(key)}] = function (module, exports, require) {\n${fs.readFileSync(f, "utf8")}\n};\n`;
}
out += `function __resolve(from, req) {
  const base = from.split("/").slice(0, -1);
  for (const part of req.split("/")) {
    if (part === ".") continue;
    if (part === "..") base.pop();
    else base.push(part);
  }
  let p = base.join("/");
  if (!p.endsWith(".js")) p += ".js";
  if (!__mods[p]) p = p.replace(/\\.js$/, "/index.js"); // require("./emit") style
  return p;
}
function __require(from, req) {
  const key = __resolve(from, req);
  if (__cache[key]) return __cache[key].exports;
  const mod = { exports: {} };
  __cache[key] = mod;
  __mods[key](mod, mod.exports, (r) => __require(key, r));
  return mod.exports;
}
window.FoundryTranspile = __require("src/x", "./index");
})();
`;
fs.writeFileSync(path.join(__dirname, "transpile.bundle.js"), out);

// ---- embedded examples ---------------------------------------------------------
const EXAMPLES = [
  { label: "showcase (MiniLang)", from: "mini", file: "examples/showcase.ml" },
  { label: "fizzbuzz (MiniLang)", from: "mini", file: "examples/fizzbuzz.ml" },
  { label: "structs (MiniLang)", from: "mini", file: "examples/structs.ml" },
  { label: "loops (MiniLang)", from: "mini", file: "examples/loops.ml" },
  { label: "classes (JavaScript)", from: "js", file: "examples/js/shapes.js" },
  { label: "classes (Python)", from: "python", file: "examples/py/shapes.py" },
  { label: "classes (TypeScript)", from: "ts", file: "examples/ts/shapes.ts" },
  { label: "arrays (C)", from: "c", file: "examples/c/arrays.c" },
];
const blob = EXAMPLES.map((e) => ({
  label: e.label, from: e.from,
  source: fs.readFileSync(path.join(ROOT, e.file), "utf8"),
}));
fs.writeFileSync(path.join(__dirname, "examples.js"),
  "// generated by playground/build.js — do not edit\nwindow.FoundryExamples = " + JSON.stringify(blob, null, 1) + ";\n");

console.log(`playground: bundled ${files.length} modules + ${blob.length} examples`);
