// generated by playground/build.js — do not edit
window.FoundryExamples = [
 {
  "label": "showcase (MiniLang)",
  "from": "mini",
  "source": "struct Item {\n  name: string;\n  qty: int;\n  price: float;\n}\n\nfunc total(items: Item[]): float {\n  let sum: float = 0.0;\n  for (let i: int = 0; i < len(items); i = i + 1) {\n    sum = sum + items[i].price * float(items[i].qty);\n  }\n  return sum;\n}\n\nfunc tag(it: Item): string {\n  return it.name + \" x\" + it.qty + (it.qty > 1 ? \" (bulk)\" : \"\");\n}\n\nfunc main(): void {\n  let items: Item[] = [Item(\"anvil\", 2, 19.5), Item(\"tongs\", 1, 7.25), Item(\"flux\", 6, 0.5)];\n  for (let i: int = 0; i < len(items); i = i + 1) {\n    if (items[i].qty == 0) { continue; }\n    print(tag(items[i]));\n  }\n  print(total(items));\n  print(int(total(items)));\n  print(substr(\"=== FOUNDRY ===\", 4, 11));\n  print(len(items) >= 3);\n}\n"
 },
 {
  "label": "fizzbuzz (MiniLang)",
  "from": "mini",
  "source": "// FizzBuzz — exercises if/else-if chains, modulo, and printing both ints and strings.\nfunc main(): void {\n  let i: int = 1;\n  while (i <= 20) {\n    if (i % 15 == 0) {\n      print(\"FizzBuzz\");\n    } else if (i % 3 == 0) {\n      print(\"Fizz\");\n    } else if (i % 5 == 0) {\n      print(\"Buzz\");\n    } else {\n      print(i);\n    }\n    i = i + 1;\n  }\n}\n"
 },
 {
  "label": "structs (MiniLang)",
  "from": "mini",
  "source": "struct Point {\n  x: int;\n  y: int;\n}\n\nstruct Label {\n  name: string;\n  hits: int;\n}\n\nfunc translate(p: Point, dx: int, dy: int): void {\n  p.x = p.x + dx;\n  p.y = p.y + dy;\n}\n\nfunc manhattan(p: Point): int {\n  let ax: int = p.x;\n  let ay: int = p.y;\n  if (ax < 0) { ax = 0 - ax; }\n  if (ay < 0) { ay = 0 - ay; }\n  return ax + ay;\n}\n\nfunc origin_dist(): int {\n  return manhattan(Point(3, -4));\n}\n\nfunc bump(l: Label): void {\n  l.hits = l.hits + 1;\n  l.name = l.name + \"*\";\n}\n\nfunc main(): void {\n  let p: Point = Point(3, 4);\n  print(p.x);\n  print(p.y);\n  translate(p, 10, -2);\n  print(p.x);\n  print(p.y);\n  print(manhattan(p));\n  print(origin_dist());\n\n  let tag: Label = Label(\"build\", 1);\n  bump(tag);\n  bump(tag);\n  print(tag.name + \":\" + tag.hits);\n}\n"
 },
 {
  "label": "loops (MiniLang)",
  "from": "mini",
  "source": "func main(): void {\n  let total: int = 0;\n  for (let i: int = 0; i < 10; i = i + 1) {\n    if (i % 2 == 0) { continue; }\n    if (i > 7) { break; }\n    total = total + i;\n  }\n  print(total);\n\n  let n: int = 0;\n  while (true) {\n    n = n + 1;\n    if (n % 3 != 0) { continue; }\n    print(n);\n    if (n >= 9) { break; }\n  }\n\n  let s: int = 0;\n  for (let j: int = 0; j < 4; j = j + 1) {\n    for (let k: int = 0; k < 4; k = k + 1) {\n      if (k == j) { continue; }\n      if (k == 3) { break; }\n      s = s + 1;\n    }\n  }\n  print(s);\n}\n"
 },
 {
  "label": "classes (JavaScript)",
  "from": "js",
  "source": "// Real JavaScript classes become IR structs: field types are inferred from\n// `new` call sites, and mutation through a function works on every target.\nclass Point {\n  constructor(x, y) {\n    this.x = x;\n    this.y = y;\n  }\n}\n\nclass Score {\n  constructor(label, points) {\n    this.label = label;\n    this.points = points;\n  }\n}\n\nfunction translate(p, dx, dy) {\n  p.x += dx;\n  p.y += dy;\n}\n\nfunction award(s, n) {\n  s.points += n;\n  s.label = s.label + \"+\";\n}\n\nfunction main() {\n  let p = new Point(2, 3);\n  translate(p, 5, -1);\n  console.log(p.x);\n  console.log(p.y);\n  console.log(p.x * p.y);\n\n  let s = new Score(\"level\", 10);\n  award(s, 32);\n  award(s, 8);\n  console.log(s.label + \": \" + s.points);\n  console.log(s.points > 49);\n}\n\nmain();\n"
 },
 {
  "label": "classes (Python)",
  "from": "python",
  "source": "# Real Python classes become IR structs: field types are inferred from the\n# __init__ call sites, and mutation through a function works on every target.\nclass Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\nclass Tally:\n    def __init__(self, label, count):\n        self.label = label\n        self.count = count\n\ndef translate(p, dx, dy):\n    p.x += dx\n    p.y += dy\n\ndef bump(t, n):\n    t.count += n\n    t.label = t.label + \"!\"\n\ndef main():\n    p = Point(2, 3)\n    translate(p, 5, -1)\n    print(p.x)\n    print(p.y)\n    print(p.x * p.y)\n    t = Tally(\"run\", 1)\n    bump(t, 4)\n    bump(t, 5)\n    print(t.label)\n    print(t.count)\n\nmain()\n"
 },
 {
  "label": "classes (TypeScript)",
  "from": "ts",
  "source": "// TypeScript classes with parameter properties become IR structs — the field\n// types are written down, so no inference is needed (floats included).\nclass Vec2 {\n  constructor(public x: float, public y: float) {}\n}\n\nclass Player {\n  constructor(public name: string, public hp: int) {}\n}\n\nfunction dot(a: Vec2, b: Vec2): float {\n  return a.x * b.x + a.y * b.y;\n}\n\nfunction damage(p: Player, n: int): void {\n  p.hp -= n;\n  p.name = p.name + \"*\";\n}\n\nfunction main(): void {\n  let v: Vec2 = new Vec2(1.5, 2.0);\n  let w = new Vec2(0.5, 4.0);\n  console.log(dot(v, w));\n  v.x += 1.0;\n  console.log(v.x + v.y);\n\n  let hero = new Player(\"ranger\", 30);\n  damage(hero, 12);\n  damage(hero, 5);\n  console.log(hero.name + \" \" + hero.hp);\n  console.log(hero.hp < 15);\n}\n\nmain();\n"
 },
 {
  "label": "arrays (C)",
  "from": "c",
  "source": "/* Real C with arrays: literal init, the sizeof length idiom, a zero-filled\n * declaration, and in-place mutation through functions taking `int a[]` and\n * `int*` params. Transpiles to the other 7 languages, all matching the\n * original C's output. */\n#include <stdio.h>\n\nint sum(int a[], int n) {\n    int total = 0;\n    for (int i = 0; i < n; i++) {\n        total += a[i];\n    }\n    return total;\n}\n\nvoid scale(int* a, int n, int k) {\n    for (int i = 0; i < n; i++) {\n        a[i] = a[i] * k;\n    }\n}\n\nint main(void) {\n    int data[] = {3, 1, 4, 1, 5, 9, 2, 6};\n    int n = sizeof(data) / sizeof(data[0]);\n    printf(\"count: %d\\n\", n);\n    printf(\"sum: %d\\n\", sum(data, n));\n    scale(data, n, 2);\n    printf(\"doubled sum: %d\\n\", sum(data, n));\n    printf(\"last: %d\\n\", data[n - 1]);\n\n    int squares[5];\n    for (int i = 0; i < 5; i++) {\n        squares[i] = i * i;\n    }\n    squares[0]++;\n    squares[1] += 10;\n    printf(\"square sum: %d\\n\", sum(squares, 5));\n    return 0;\n}\n"
 }
];
